Redux toolkit
EgorRyazanov/cherry-pies-game pull request #18
Opened 2023-10-28 14:33 UTC by tata1988

Данная ветка предназначена для индивидуального зачета, прошу после апрува не мержить
1. Добавлен в проект redux-toolkit.
2. Добавлен userSlice для user
3. После авторизации информация о user добавляется в userSlice в App.

2023-10-28 21:35 UTC, EgorRyazanov approved these changes

2023-10-28 21:35 UTC, EgorRyazanov commented on packages/client/src/App.tsx
> +        })
Предлагаю всю эту логику вынести в thunk или rtk query

2023-10-28 21:35 UTC, EgorRyazanov commented on packages/client/src/store/index.tsx
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
Предлагаю вынести эти хуки в отдельные файлы

2023-10-28 21:35 UTC, EgorRyazanov commented on packages/client/src/store/reducers/user.ts
> +}
Предлагаю вынести начальный стейт в отдельный файл рядом с текущим слайсом. Также вижу смысл сделать отдельный тип для него

2023-10-29 08:19 UTC, tata1988 commented on packages/client/src/store/index.tsx
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector
перенесла в папку hoc

2023-10-29 09:14 UTC, tata1988 commented on packages/client/src/store/reducers/user.ts
> +}
вынесла в отдельный файл state

2023-10-29 11:40 UTC, Olegas commented on packages/client/src/App.tsx
> +        })
Поддерживаю, правильное замечание!

2023-10-29 11:42 UTC, Olegas requested changes
Добрый день.
Согласен с замечание о выносе асинхронных запросов в thunk
Давайте доработаем.

2023-10-29 19:27 UTC, tata1988 commented on packages/client/src/App.tsx
> +        })
вынесла в thunk

2023-10-29 19:46 UTC, EgorRyazanov approved these changes

2023-10-29 19:46 UTC, EgorRyazanov commented on packages/client/src/store/user/slice.tsx
> +
Круто! Вынеси еще это в отдельный файл - dispatchers или actions в папке user

2023-10-30 21:22 UTC, Olegas requested changes
Стало лучше, но в реализации есть ошибки. Написал комментарии

2023-10-30 21:22 UTC, Olegas commented on packages/client/src/store/user/slice.tsx
> +  const data = await response.data
Тут не надо await, это же просто поле в объекте

2023-10-30 21:22 UTC, Olegas commented on packages/client/src/App.tsx
> +        dispatch(getUser())
Если тут хочется поймать ошибку метода, то так не получится. Во-первых тут нужен await т.к. иначе ты просто получишь в ответ промис и никаких исключений не будет
Во-вторых, при использовании async thunk нужно делать unwrap() если ты хочешь получить ошибку, вот документация: https://redux-toolkit.js.org/api/createAsyncThunk#unwrapping-result-actions

2023-10-31 02:55 UTC, tata1988 commented on packages/client/src/store/user/slice.tsx
> +
вынесла в actions

2023-10-31 02:56 UTC, tata1988 commented on packages/client/src/store/user/slice.tsx
> +  const data = await response.data
убрала

2023-10-31 03:13 UTC, tata1988 commented on packages/client/src/App.tsx
> +        dispatch(getUser())
убрала try catch

2023-10-31 09:37 UTC, EgorRyazanov commented on packages/client/src/store/user/slice.tsx
> +        state.error = action.payload as string
Можно избавиться от as проверкой. Как пример:
![image](https://github.com/EgorRyazanov/cherry-pies-game/assets/89483642/d53096bf-2f4e-404a-93be-4d1156085684)

2023-10-31 10:02 UTC, tata1988 commented on packages/client/src/store/user/slice.tsx
> +        state.error = action.payload as string
спасибо, внедрю после проверки

2023-10-31 14:48 UTC, Olegas approved these changes
Работа принята

2023-10-31 15:01 UTC, merged