feature_(WithAuthCheck): add HOC WithAuthCheck_31.10.23.
EgorRyazanov/cherry-pies-game pull request #20
Opened 2023-10-31 05:38 UTC by EvgeniyGrokholskiy

### Какую задачу решаем
Добавить HOC для проверки авторизации пользователя и автоматического перенаправления уже авторизованных пользователей на главную страницу со страницы авторизации или регистрации.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-31 09:29 UTC, EgorRyazanov approved these changes

2023-11-01 08:11 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Здорово постарались!

Есть несколько замечаний, предлагаю ознакомиться и поправить

Хорошего дня :)

2023-11-01 08:11 UTC, IvanPeleshok commented on packages/client/src/hoc/WithAuthCheck/index.tsx
> +    }, [pathname])
Так и должно быть, что на каждое изменение `pathname` будет вызываться метод getUserData?

Не будут ли лишние запросы, когда данные уже получены?

2023-11-01 08:11 UTC, IvanPeleshok commented on packages/client/src/hoc/WithAuthCheck/index.tsx
> +        .then(() => {
Предлагаю переписать на async / await + try / catch
Избавляясь от колбеков, пишем в синхронной стилистике, читаемость в разы выше

Предлагаю поправить во всём MR

2023-11-01 08:11 UTC, IvanPeleshok commented on packages/client/src/hook/useAuth.tsx
Аналогичные вопросы

2023-11-01 09:18 UTC, EvgeniyGrokholskiy commented on packages/client/src/hoc/WithAuthCheck/index.tsx
> +    }, [pathname])
Была идея проверять авторизован пользователь или нет при переходе на каждую страницу и если он не авторизован перенаправлять его на страницу авторизации.
Этот же компонент осуществляет авто вход, если куки валидны и пользователь зашел на страницу авторизации/регистрации.

2023-11-02 07:26 UTC, IvanPeleshok commented on packages/client/src/hoc/WithAuthCheck/index.tsx
> +    }, [pathname])
Не кажется ли тебе это избыточным?

Нам достаточно один раз проверить этот момент и отправить на страницу логина / нетребующую авторизации и запретить переход на другие страницы в случае отрицательного ответа от сервера

Предлагаю реализовать данный момент через функционал
Если сервер единожды дал положительный ответ, что пользователь авторизован, то нет смысла на каждый "чих" отправлять запросы, пока кука не умерёт при новой авторизации или разлогине

2023-11-02 07:28 UTC, IvanPeleshok requested changes
Нужны доработки

2023-11-02 09:04 UTC, EvgeniyGrokholskiy commented on packages/client/src/hoc/WithAuthCheck/index.tsx
> +    }, [pathname])
Вынес локальные переменные в слайс, добавил редьюсеры для их изменения.

2023-11-03 07:40 UTC, IvanPeleshok commented on packages/client/src/store/user/actions.tsx
> +  const response = await authApi.getUserData()
Необходимо обрабатывать реджект промиса, иначе можно словить исключение

2023-11-03 07:41 UTC, IvanPeleshok approved these changes
Замечательно реализовали!
Поздравляю, апрув

Хорошего дня :)

2023-11-03 07:51 UTC, merged