добавлен notification-api, уведомление на главной странице
EgorRyazanov/cherry-pies-game pull request #28
Opened 2023-11-26 10:58 UTC by tata1988

Добавлен notification-api . На главной странице всплывает уведомление на 10сек.

2023-11-26 11:05 UTC, Aristockij approved these changes

2023-11-26 15:41 UTC, IvanPeleshok commented on packages/client/src/pages/Main/index.tsx
> +    useNotification(data)
Получается, что мы внутри хука вызываем кастомный хук, что довольно странно

Предлагаю внутри хука useNotification вызвать useEffect и там реализовать необходимую вам логику

2023-11-26 15:41 UTC, IvanPeleshok commented on packages/client/src/hook/useNotification.tsx
> +    }, 10 * 1000)
Предлагаю вынести в константу, чтобы код был более человекочитаемым

2023-11-26 15:43 UTC, IvanPeleshok commented on packages/client/src/hook/useNotification.tsx
> +    const permission = await Notification.requestPermission()
Если промис вернётся с отклонением, то код упадёт, предлагаю обработать его с помощью try / catch
https://caniuse.com/mdn-api_notification_requestpermission_static

2023-11-26 15:43 UTC, IvanPeleshok commented on packages/client/src/hook/useNotification.tsx
> +  granted ? showNotification() : console.log('Error')
Ошибка не имеет практически никакой информации, возможно в этом случае, хотя бы текст ошибки подправить?

2023-11-26 15:44 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Оставил комментарии по улучшению реализации фичи
Предлагаю доработать

Хорошего дня :)

2023-11-26 16:58 UTC, tata1988 commented on packages/client/src/pages/Main/index.tsx
> +    useNotification(data)
вынесла из хуков

2023-11-26 16:58 UTC, tata1988 commented on packages/client/src/hook/useNotification.tsx
> +    }, 10 * 1000)
разве не в константе сейчас? const timer

2023-11-26 16:59 UTC, tata1988 commented on packages/client/src/hook/useNotification.tsx
> +    const permission = await Notification.requestPermission()
добавила try / catch

2023-11-26 16:59 UTC, tata1988 commented on packages/client/src/hook/useNotification.tsx
> +  granted ? showNotification() : console.log('Error')
изменила текст на You blocked the notifications

2023-11-27 12:56 UTC, IvanPeleshok commented on packages/client/src/hook/useNotification.tsx
> +    }, 10 * 1000)
Вы про то, что возвращает  setTimeout?
Не, я говорю про 10 * 1000

2023-11-27 16:36 UTC, IvanPeleshok commented on packages/client/src/pages/Main/index.tsx
> +    notificationApi(data)
Не очень корректное название доя того, функции, которая вызывает showNotification

Такое ощущение, что можно назвать просто showNotification без дополнительных обёрток

Предлагаю посмотреть на что-то подобное:
https://codesandbox.io/p/sandbox/react-notifications-api-hook-nhl9b

2023-11-27 16:37 UTC, IvanPeleshok commented on packages/client/src/utils/notificationApi.tsx
> +    granted ? showNotification() : console.log('You blocked the notifications')
Возможно вы не только в консоль хотите отображать сообщение, но и на UI, чтобы пользователь понимал почему не работает функционал?

2023-11-27 16:37 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечания
Поздравляю, апрув 🚀 

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-11-28 15:44 UTC, merged