Api develop
EgorRyazanov/cherry-pies-game pull request #36
Opened 2023-12-10 04:42 UTC by ilinaro

### Какую задачу решаем
Добавлены api, дока для удобства подключения,  добавлен xss sequelize
Есть дополнительные роуты, которые будут подключены на неделе доработки. 
Добавлен Docker-Compose для субд. Так же ожидается Docker фронта для сборки всего проекта.

### Скриншоты/видяшка (если есть)
<img width="263" alt="Снимок экрана 2023-12-10 в 09 40 50" src="https://github.com/EgorRyazanov/cherry-pies-game/assets/87081323/d658c27a-4c9b-4d8c-85d6-523125e4e5f1">

2023-12-10 05:08 UTC, EvgeniyGrokholskiy approved these changes

2023-12-10 07:45 UTC, Olegas commented on docker-compose.pgadmin.yml
> +    restart: unless-stopped
Тут нужна зависимость от контейнера postgres. Если база не стартовала то в админке нет смысла

2023-12-10 07:49 UTC, Olegas commented on packages/server/src/models/comment.model.ts
> +    topic_id: {
Комментарии запрашиваются по ид топика. Значит на это поле нужен индекс

2023-12-10 07:51 UTC, Olegas commented on packages/server/src/controller/topic.controller.ts
> +  async updateTopic(req: Request, res: Response) {
Совет: Когда будете делать изменение и удаление, не забудьте сделать проверку что действие выполяет автор. У вас сейчас автор даже не сохраняется в БД

2023-12-10 07:52 UTC, Olegas requested changes
Добрый день.
В целом все хорошо, но есть одна важная проблема, которую нужно исправить - наличие индекса на таблице. Написал по ней отдельный комментарий в коде.
Еще добавил пару советов - они не критичны для приемки.

2023-12-11 15:56 UTC, Olegas approved these changes
Работа принята

2023-12-11 19:20 UTC, merged