Canvas engine
EgorRyazanov/cherry-pies-game pull request #7
Opened 2023-10-22 14:09 UTC by Aristockij

добавил первую версию движка в useEffect в компоненте Canvas

2023-10-22 14:11 UTC, EvgeniyGrokholskiy approved these changes
Принимаю

2023-10-22 15:00 UTC, Olegas requested changes
Добрый день.
Есть проблемы по коду - написал комментарии.
В общем, основное:
1. Все константы, объекты, которые не меняются, классы - надо вынести за границы компонента и не создавать каждый раз. Лучше вообще в отдельный файлы - актуально для классов
2. Анимацию надо останавливать при разборке компонента
3. Если поставил подписку на событие - надо отписаться при разрушении компонента

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    ]
Если эти два массива не изменяются в процессе работы приложения, их лучше определить один раз за пределами компонента.

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    const width = 800
И другие константы - тоже лучше определить один раз

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    class Rect {
Классы, необходимые для работы - аналогично, вынести и определить один раз. Лучше сразу вынести в отдельный файл, что бы было проще читать

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +        const localContext = context
Зачем определять localContext если он уже есть в аргументах?

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +        if (context) {
А вот это странновато. Тут ты используешь значение из замыкания. Лучше контекст передать либо в аргументы либо в конструктор

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +          if (context) {
Эту проверку надо вынести куда-то выше. Иначе сейчас получается что контекста нет, гоним два вложенных цикла что бы потом сделать ничего.

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +        building.target = null
Зачем сбрасывать в null и сразу же менять на другое значение? В этом нет необходимости, эту строку можно убрать т.к. дальше идет присвоение validEnemies[0]

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    canvas.addEventListener('click', () => {
Если есть подписка на события - должна быть отписка в случае разрушения компонента

2023-10-22 15:00 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +      requestAnimationFrame(updateAnimation)
Из цикла анимации должен быть выход. Как минимум игра может закончиться а еще компонент может разрушиться если пользователь перешел на другую страницу

2023-10-23 11:40 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +          if (context) {
Замечание не исправлено

2023-10-23 11:45 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +  waypoints,
enemies и waypoints не надо делать глобальными, их надо объявить где-то в районе эффекта, который запускает анимацию и объявляет обработчики. Пока бежит анимация, у нее будет доступ к этим массивам. Если их сложить глобально - они "выживут" после остановки игры и будет утечка памяти.

2023-10-23 11:45 UTC, Olegas requested changes
Добрый день.
Стало лучше, но не до конца. Написал еще пару комментариев.
Нужно доработать

2023-10-23 19:47 UTC, Olegas requested changes
Нельзя переменные объявлять внутри компонента. Каждый раз когда компонент по какой-либо причине перерисуется, все переменные будут сброшены и переинициализированы заново. Если доступ к ним нужно иметь внутри цикла анимации, на каждом шаге, их надо объявить в замыкании, внутри useEffect, так что бы всем функциям внутри они были доступны. useEffect (т.к. у него пустые зависимости) отработает один раз за время жизни компонента.

2023-10-23 19:47 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +      mouse.x = e.clientX
Вот здесь должен быть `let mouse = {}`

2023-10-23 19:47 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    const canvas = refCanvas.current
Вот на этой строке должно быть `const enemies: Enemy[] = []` - иначе при перерендере компонента enemies обнулится

2023-10-23 19:47 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    const canvas = refCanvas.current
Еще тут должно быть `let animationFrame = 0` по той же причине. Если компонент перестроится эта переменная будет сброшена.

2023-10-23 19:47 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +    const canvas = refCanvas.current
activeBuildPlace - тоже должен быть внутри эффекта, по той же причине

2023-10-23 20:22 UTC, Aristockij commented on packages/client/src/components/Canvas/Canvas.tsx
> +      mouse.x = e.clientX
я не знаю как лучше сделать, потому что mouse использует не только mouseActiveBuildPlace  но и внутри перебора towersPlace.forEach. поэтому просто вынес все в useEffect

2023-10-23 20:25 UTC, Olegas commented on packages/client/src/components/Canvas/Canvas.tsx
> +      mouse.x = e.clientX
А, вот оно что... Я почему-то проглядел это место и никак не мог понять зачем ты выносишь так высоко эту переменную. Ну тогда ее просто надо внутрь эффекта занести хотя бы

2023-10-24 17:09 UTC, Olegas approved these changes
Работу принимаю.
Но обрати внимание пожалуйста на массивы в файле const.ts - они подвержены той же проблеме, что и enemies, пока ты их не вынес в основной цикл движка. Их бы тоже вынести.

2023-10-24 17:52 UTC, EgorRyazanov approved these changes

2023-10-30 08:03 UTC, merged